[package]
name = "xml_conn"
version = "0.1.0"
authors = ["Di Chen <dichen@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlrpc = "0.13.1"
reqwest = "0.9.20"
